WebSite/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using WebSite.Areas.Identity.Data;
using WebSite.Models;

namespace WebSite.Models
{
    public class Order
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime OrderDate { get; set; }

        // Foreign key property
        public int StatusId { get; set; }

        public int AdressDetailID { get; set; }

        // Navigation property for the one-to-one relationship
        public OrderStatus Status { get; set; }

        public CustomerAdressDetail adressDetail { get; set; }

        public List<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
    }

    public class CustomerAdressDetail
    {
        public int ID { get; set; }

        public string PhoneNumber {  get; set; }

        public string FullName { get; set; }

        public string DeliverySity { get; set; }

        public string PostDepartment { get; set; }


    }
}

WebSite/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebSite.Data;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Orders.Include(o => o.Status);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["StatusId"] = new SelectList(_context.OrderStatus, "Id", "StatusName", order.StatusId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Order order)
        {
            var _order = await _context.Orders.FindAsync(id);
            try
            {
                _order.Status.StatusName = order.Status.StatusName;
                _order.Status.StatusDescription = order.Status.StatusDescription;
            
                // Mark the entity as modified and save changes
                _context.Entry(_order).State = EntityState.Modified;
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrderExists(order.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("GetAllUsersOrders", "GetAllUsersOrders");
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebSite/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using WebSite.Areas.Identity.Data;
using WebSite.Data;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public ProductsController(IHttpContextAccessor http, UserManager<ApplicationUser> user, ApplicationDbContext context)
        {
            _httpContextAccessor = http;
            _userManager = user;
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var shoppingContext = _context.Products.Include(p => p.Category);
            return View(await shoppingContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }
            var product = await _context.Products
               .Include(p => p.Category).Include(p => p.Variants)
               .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            var user = GetUserId();
            if (user != null)
            {
                var LastVisited = new LastVisited()
                {
                    ProductID = id.ToString(),
                    UserId = user
                };
                if (_context.LastVisitedsProducts.Any(e => e.UserId == user && e.ProductID == id.ToString()))
                    return View(product);
                else
                {
                    var product_add = _context.LastVisitedsProducts.Add(LastVisited);
                    _context.SaveChanges();
                }
            }
            return View(product);
        }


        // GET: Products/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(ProductCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Створіть новий продукт та додайте варіанти одягу
                var product = new Product
                {
                    Name = model.Name,
                    Description = model.Description,
                    Price = model.Price,
                    DiscountedPrice = model.DescountedPrice,
                    Photo = model.Photo,
                    CategoryId = model.CategoryId,
                    Variants = new List<ClothingVariant>()
                };

                foreach (var sizeInfo in model.SizesInfo)
                {
                    product.Variants.Add(new ClothingVariant
                    {
                        Size = Enum.Parse<ClothingSize>(sizeInfo.Size),
                        Quantity = sizeInfo.Quantity
                    });
                }

                // Додайте новий продукт до бази даних і збережіть зміни
                _context.Products.Add(product);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(x => x.Variants)
                .Include(x => x.Category)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,DescountedPrice,Amount,Photo,CategoryId")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", product.CategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'ShoppingContext.Products'  is null.");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.Products?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [HttpPost]
        public async Task<bool> AddToFavourite(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return false;
            }

            var user = GetUserId();
            var product = await _context.Products.FindAsync(id);
            if (product != null && user != null)
            {
                _context.FavouriteProducts.Add(new FavouriteProducts
                {
                    UserId = user,
                    ProductID = product.Id.ToString()
                });

                await _context.SaveChangesAsync();
                return true;
            }

            return false;
        }

        [HttpPost]
        public async Task<bool> RemoveFromFavourite(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return false;
            }
            var user = GetUserId();
            var product = await _context.FavouriteProducts
                .FirstOrDefaultAsync(m => m.ProductID == id.ToString() && m.UserId == user);
            if (product != null && user != null)
            {
                _context.FavouriteProducts.Remove(product);
                await _context.SaveChangesAsync();
                return true;
            }
            return false;
            
        }

        private string GetUserId()
        {
            var principal = _httpContextAccessor.HttpContext.User;
            string userId = _userManager.GetUserId(principal);
            return userId;
        }
    }
}

WebSite/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebSite.Interfaces;

namespace WebSite.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRealization _user;
        public UserController(IUserRealization user)
        {
            _user = user;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> UserOrders()
        {
            var orders = await _user.UserOrders();
            return View(orders);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetAllUsersOrders()
        {
            var orders = await _user.GetAllUsersOrders();
            return View(orders);
        }
    }
}

WebSite/Views/Shared/Order.cshtml
@model Order
<!-- The modal -->
<div id="orderModal" class="modal">
    <div class="modal-content">
        <span class="close" id="closeModalBtn">&times;</span>
        <form asp-action="Checkout">
            <div class="text-center">
                <h3>ОФОРМЛЕННЯ ЗАМОВЛЕННЯ</h3>
                <h6>Введіть усю необхідну інформацію для доставки товару</h6>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="adressDetail.FullName" class="control-label"></label>
                <input asp-for="adressDetail.FullName" class="form-control" />
                <span asp-validation-for="adressDetail.FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="adressDetail.PhoneNumber" class="control-label"></label>
                <input type="number" asp-for="adressDetail.PhoneNumber" class="form-control" />
                <span asp-validation-for="adressDetail.PhoneNumber" class="text-danger"></span>
            </div>
            <input type="text" class="form-control" id="cityName" name="cityName" placeholder="Введіть назву населеного пункту:">
            <select asp-for="adressDetail.DeliverySity" type="hidden" id="selectedCity" value="" style="visibility:hidden">
                <option value="" disabled>Виберіть місто</option>
            </select>
            <select asp-for="adressDetail.PostDepartment" type="hidden" id="selectedDepartment" value="" style="visibility:hidden">
                <option value="" disabled>Виберіть відділення</option>
            </select>
            <div class="my-2 d-flex justify-content-between">
                <span id="saveSelected" class="btn btn-primary mt-2">Пошук Населеного Пункту</span>
                <span id="findDepartment" class="btn btn-primary mt-2">Пошук Відділення</span>
            </div>
            <div class="my-2 d-flex justify-content-center">
                <button class="btn btn-primary" type="submit">Оформити замовлення</button>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var saveSelectedButton = document.getElementById("saveSelected"); //кнопка пошуку міста
        var cityNameInput = document.getElementById("cityName");                //місто яке вводимо
        var findDepartment = document.getElementById("findDepartment");  //кнопка пошуку відділення

        saveSelectedButton.addEventListener("click", function () {
            var cityName = cityNameInput.value;
            $.ajax({
                type: "POST",
                url: '/NovaPoshta/SearchSettlements?cityName=' + cityName,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    // Отримайте посилання на існуючий елемент <select> за його id
                    var selectElement = document.getElementById("selectedCity");
                    // Очистіть всі поточні опції
                    selectElement.innerHTML = "";

                    data.forEach(function (settlement) {
                        // Створіть нову опцію
                        var optionElement = document.createElement("option");
                        optionElement.value = settlement.settlementTypeCode + ' ' + settlement.mainDescription + ' ' + settlement.area + "область " + settlement.region + " район";
                        optionElement.dataset.value = settlement.deliveryCity;
                        // Встановлення тексту внутрішнього HTML для опції
                        optionElement.innerHTML = `${settlement.settlementTypeCode} ${settlement.mainDescription} ${settlement.area} область ${settlement.region} район`;

                        // Додайте опцію до існуючого елемента <select>
                        selectElement.appendChild(optionElement);
                    });
                    selectElement.style.visibility = "visible"; // Set the visibility to "visible"
                },
                error: function () {
                    alert("Помилка при завантаженні даних.");
                }
            });
        });

        findDepartment.addEventListener("click", function () {
            var selectedCity = document.getElementById("selectedCity").querySelector('option:checked').dataset.value;
            if (selectedCity) {
                $.ajax({
                    type: "POST",
                    url: '/NovaPoshta/SaveSettlements?cityRef=' + selectedCity,
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (data) {
                        var selectElement = document.getElementById("selectedDepartment"); // Отримуємо посилання на другий select

                        selectElement.innerHTML = ""; // Очищаємо всі поточні опції

                        data.forEach(function (settlement) {
                            // Створюємо нову опцію для другого select
                            var optionElement = document.createElement("option");
                            optionElement.value = settlement.description; // Значення опції

                            // Встановлення тексту внутрішнього HTML для опції
                            optionElement.innerHTML = `${settlement.description}`;

                            // Додаємо опцію до другого select
                            selectElement.appendChild(optionElement);
                        });
                        selectElement.style.visibility = "visible";
                    },
                    error: function () {
                        alert("Помилка при завантаженні даних.");
                    }
                });
            } else {
                alert("Виберіть спочатку місто");
            }
        });
    });
</script>

WebSite/Views/Shared/ProductList.cshtml
@using WebSite.Interfaces
@using WebSite.Areas.Identity.Data;
@using Microsoft.AspNetCore.Identity
@inject IProductRealization _product
@inject IUserRealization _user
@inject UserManager<ApplicationUser> UserManager
@model bool

@{
    // Отримайте параметр showDiscountedOnly з часткового представлення
    var products = _product.ProductList(@Model);
    var user = _user;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopeee</title>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="sweetalert2.min.js"></script>
    <link rel="stylesheet" href="sweetalert2.min.css">
</head>
<body>
        <div class="products">
            @foreach (var product in products)
            {
                <div class="product-card">
                    @if (product.DiscountedPrice != null)
                    {
                        <div class="discount-badge">
                            <span class="discount-text">On Sale</span>
                        </div>
                    }
                    <div class="product-image">
                        <img src="@product.Photo" alt="@product.Name" />
                    </div>
                    <div class="produnt-info">
                        <div class="product-name">@product.Name</div>
                        <div class="product-description">@product.Description</div>
                        <div class="product-price">
                            @if (product.DiscountedPrice != null)
                            {
                                <div class="price-wrapper">
                                    <div class="original-price">@product.Price грн</div>
                                    <div class="discounted-price">@product.DiscountedPrice грн</div>
                                </div>
                            }
                            else
                            {
                                <div class="price-wrapper">
                                    <div class="discounted-price">@product.Price грн</div>
                                </div>
                            }
                        </div>
                    </div>


                    <div class="btn-group">
                    <a asp-action="Details" asp-controller="Products" asp-route-id="@product.Id" class="btn btn-danger">Buy</a>
                    <span data-id="@product.Id" id="addtofavouritebtn" data-islogin="@(_user.GetUserId() != null ? _user.GetUserId().ToString() : "null")" class="btn btn-danger @(user.IsLikedProductAsync(product.Id).Result ? "liked" : "")">
                        @(user.IsLikedProductAsync(product.Id).Result ? "♥" : "♡")
                    </span>
                    </div>
                </div>
            }
        </div>
</body>
</html>
<script>
    var addToFavouriteBtn = document.querySelectorAll("#addtofavouritebtn");
    var stateMap = {};
    for (let i = 0; i < addToFavouriteBtn.length; i++) {
        var btn = addToFavouriteBtn[i];
        btn.addEventListener("click", function () {
            var isLiked = this.classList.contains("liked");
            var productID = this.getAttribute("data-id"); // Отримуємо productID для поточного елемента
            var isUserLogin = this.getAttribute("data-islogin");
            if (!isUserLogin || isUserLogin === 'null') {
                Swal.fire({
                    text: 'Зареєструйтесь спочатку',
                    icon: 'info',
                    confirmButtonText: 'OK!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // Redirect the user to the desired page
                        window.location.href = '/';
                    }
                });
            }
            stateMap[productID] = isLiked;
            var currentBtn = this; // Зберігаємо поточний елемент

            if (!stateMap[productID]) {
                $.ajax({
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    url: "/Products/AddToFavourite?id=" + productID,
                    success: function (data) {
                        currentBtn.textContent = "♥";
                        currentBtn.classList.add("liked");
                        stateMap[productID] = true;
                    },
                    error: function () {
                        alert("Помилка при завантаженні даних.");
                    }
                });
            } else {
                $.ajax({
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    url: "/Products/RemoveFromFavourite?id=" + productID,
                    success: function (data) {
                        currentBtn.textContent = "♡";
                        currentBtn.classList.remove("liked");
                        stateMap[productID] = false;
                    },
                    error: function () {
                        alert("Помилка при завантаженні даних.");
                    }
                });
            }
        });
    }
</script>

WebSite/Views/Shared/_Layout.cshtml
@using WebSite.Areas.Identity.Data;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebSite.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SHOPEEE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Create">Create</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetAllUsersOrders">Orders</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial">
                </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>